export const CoinActions = {
  FETCH_COIN_REQUEST: "FETCH_COIN_REQUEST",
  FETCH_COIN_SUCCESS: "FETCH_COIN_SUCCESS",
  FETCH_COIN_FAILURE: "FETCH_COIN_FAILURE",
  FETCH_ONE_COIN_REQUEST: "FETCH_ONE_COIN_REQUEST",
  FETCH_ONE_COIN_SUCCESS: "FETCH_ONE_COIN_SUCCESS",
  FETCH_ONE_COIN_FAILURE: "FETCH_ONE_COIN_FAILURE",
}
